name: Deploy

# Controls when the action will run. 
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.UNIBASE_CONTINUOUS_DEPLOYMENT }}
        port: 22
        script: |
          cd /var/www/softwarehub.uk/html/apps
          git pull origin master
          git status
          npm install
